In [73]:
def calculadora(x, y, operador):
    x = float(x)
    y = float(y)
    operador = operador
    
    if operador == '1':
        print(x+y)
    elif operador == '2':
        print(x-y)
    elif operador == '3':
        print(x*y)
    elif operador == '4':
        print(x/y)
        
    else:
        print('Operação inválida')
    
numero1 = input('Escreva aqui o primeiro número: ')
numero2 = input('Escreva aqui o segundo número: ')
operacao = input('Escreva a operação: 1. soma 2. subtração 3. multiplicação 4. divisão ')

calculo = calculadora(numero1,numero2,operacao)


Escreva aqui o primeiro número: 2
Escreva aqui o segundo número: 2
Escreva a operação: 1. soma 2. subtração 3. multiplicação 4. divisão 2
0.0


In [76]:
from time import sleep

contador = 1

while contador <=5:
    print(contador)
    sleep(1)
    contador += 1


1
2
3
4
5


In [78]:
lista = [1,2,3, "4", True]
print(lista)

[1, 2, 3, '4', True]


In [2]:
lista = list(range(0,6))
print(lista)

[0, 1, 2, 3, 4, 5]


In [4]:
#numpy

import numpy as np

#criando minha primeira array
um = np.array([1,2,3,4,5])
print(um)
type(um)


[1 2 3 4 5]


numpy.ndarray

In [10]:
mtfloat = np.array([1,2,3,4], dtype = np.float64)
display(mtfloat)
print(type(mtfloat))

mtint = np.array([1,2,3,4], dtype = np.int32)
display(mtint)
print(type(mtint))

array([1., 2., 3., 4.])

<class 'numpy.ndarray'>


array([1, 2, 3, 4])

<class 'numpy.ndarray'>


In [13]:
#como alterar tipos de dados de arrays
mtnew = np.array([1.4, 3.6, -5.1, 9.42, 4.99999])
print(mtnew)
mtnewint = mtnew.astype(np.int32)
print(mtnewint)

[ 1.4      3.6     -5.1      9.42     4.99999]
[ 1  3 -5  9  4]


In [15]:
#elementos do numpy com mais de uma dimensão

mt7 = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
display(mt7)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
#criar arrays vazios 

#cria um array de duas dimensões com valores vazios
vazio = np.empty([3,2], dtype = np.int32)
print(vazio)
print('------')
#criar uma matriz 4x3 repleta de zeros
zeros = np.zeros([4, 3], dtype = np.int32)
print(zeros)
print('------')
# também pode ser repleto de 1
uns = np.ones([4,3], dtype = np.int32)
print(uns)
print('------')
#criar uma matriz quadrada, onde a diagonal principal vai ter 1, e os outros valores vão ser zeros
diagonal = np.eye(5)
print(diagonal)

[[-1142172112         503]
 [          0           0]
 [          1           0]]
------
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
------
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
------
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [23]:
#Criando valores aleatórios, entre zero e um
aleatorio = np.random.random((5))
print(aleatorio)
print('-----')
#Criando valores aleatórios de distribuição normal, que aceite valores negativos
aleatorio1 = np.random.randn((5))
print(aleatorio1)
print('-----')
#Criando uma matriz com números multiplicados por 10
aleatorio2 = (10*np.random.random((3,4)))
print(aleatorio2)
print(type(aleatorio2))
print('-----')

[0.66167829 0.24331742 0.55108974 0.4122444  0.9517532 ]
-----
[0.56145789 0.09143687 0.95545044 2.30899189 1.26409492]
-----
[[6.56812003 9.81762035 7.12101655 8.87508813]
 [2.41277167 5.0077283  8.56677745 4.53956187]
 [0.49551991 0.20350118 2.17563048 8.86895612]]
<class 'numpy.ndarray'>
-----


In [37]:
#Gerando aleatórios com sementes
#Sementes são números aleatórios, criados para testar ddados, mas que eles se repetem

seed = np.random.default_rng(1)
aleatorio3 = seed.random(3)
print(aleatorio3)

#Gerando inteiros, com limite de 0 a 10
aleatorio4 = seed.integers(10, size=(3,4))
print(aleatorio4)

[0.51182162 0.9504637  0.14415961]
[[8 9 2 3]
 [8 4 2 8]
 [2 4 6 5]]


In [39]:
#O método unique, remove repetições
unico = np.array([1,2,3,4,5,3,2,1])
unico = np.unique(unico)
print(unico)

[1 2 3 4 5]


In [45]:
#ver elementos específicos de uma matriz

tres = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])
print(tres)
print(tres[2] [2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
11


In [52]:
#funções matemáticas de uma matriz
#imprime o valor máximo
print(tres.max())
#imprime o valor mínimo
print(tres.min())
#imprime a soma dos valores
print(tres.sum())
#imprime o valor da média
print(tres.mean())
#imprime o valor do desvio padrão
print(tres.std())

12
1
78
6.5
3.452052529534663


In [57]:
#fazer slice de elementos array
quatro = np.array([1,2,3,4,5])
print(quatro[1])
print('------')
print(quatro[0:2])
print('------')
print(quatro[:4])
print('------')
print(quatro[:4:2])
print('------')
#mostra os 3 últimos elementos
print(quatro[-3:])

2
------
[1 2]
------
[1 2 3 4]
------
[1 3]
------
[3 4 5]


In [66]:
#Operações com arrays

m1 = np.array([[1,2,3,4], [4,3,2,1]])
m2 = np.array([[1,2,3,1],[6,5,4,3]])
res1 = m1+m2
print(res1)
print('------')
#As operações matemática funcionam mesmo se as matrizes tiverem tamanhos diferentes.
m3 = np.array([[1,2], [3,4], [5,6]])
m4 = np.array([1,2])
res2 = (m4*m3[0])
print(res2)


[[ 2  4  6  5]
 [10  8  6  4]]
------
[1 4]


In [83]:
#Criando expressões lógicas
logica = np.random.randn(4,3)
print(logica)
print('------')
x = (logica >0)
print(x)
print('------')
z = np.where(logica >0, 1, -1)
print(z)

[[ 1.64059381 -0.29577709  0.17408411]
 [ 0.6147765   0.03058675  1.34141312]
 [-0.78704318  0.06231452 -0.75886316]
 [-2.10328833 -0.73251763  0.46631066]]
------
[[ True False  True]
 [ True  True  True]
 [False  True False]
 [False False  True]]
------
[[ 1 -1  1]
 [ 1  1  1]
 [-1  1 -1]
 [-1 -1  1]]
